global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aahb-api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['aahb-api-gateway:8000']

  - job_name: 'aahb-agents'
    static_configs:
      - targets: ['aahb-agents:8001']  # Assuming agents expose metrics

  - job_name: 'neo4j'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['aahb-neo4j:2004']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['aahb-rabbitmq:15672']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']